# Generated by Django 3.0.6 on 2020-05-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('topic', models.CharField(choices=[('Politics', 'Politics'), ('Sport', 'Sport'), ('Opinion', 'Opinion'), ('Business', 'Business'), ('Science', 'Science'), ('Health', 'Health'), ('Style', 'Style'), ('Food', 'Food'), ('Tech', 'Tech'), ('Science', 'Science'), ('Psychology', 'Psychology'), ('Other', 'Other')], default='Opinion', max_length=30)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
            ],
        ),
    ]
