# Generated by Django 3.0.6 on 2020-05-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200529_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.Blog')),
            ],
            bases=('blogs.blog',),
        ),
        migrations.CreateModel(
            name='OtherBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.Blog')),
            ],
            bases=('blogs.blog',),
        ),
        migrations.CreateModel(
            name='PoliticsBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.Blog')),
            ],
            bases=('blogs.blog',),
        ),
        migrations.CreateModel(
            name='SportBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.Blog')),
            ],
            bases=('blogs.blog',),
        ),
        migrations.CreateModel(
            name='TechBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.Blog')),
            ],
            bases=('blogs.blog',),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
    ]
